

export const SHIPPING_ADDRESS_ADD_REQUEST = 'SHIPPING_ADDRESS_ADD_REQUEST';
export const SHIPPING_ADDRESS_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const SHIPPING_ADDRESS_FAIL = 'PRODUCT_LIST_FAIL';

